var utils = require('util');
var redis = require('redis');
var async = require('async');
var	client = redis.createClient(6379, "121.42.8.51");
client.auth('memeda');
//发布帖子：host_id:发帖者id；msg_des:消息内容msg_topic:消息标题classfication:帖子分类
//1.获取下一个帖子tid，2.
//现在post里面添加topic的内容，然后在topic里面添加topic的标题
exports.publish = function(host_id,msg_des,msg_topic,classification,call){
//	var slug = utils.slugify(msg_topic);
	var slug = msg_topic;
	var timestamp = Date.now();
	async.auto({
		//1.得到nextpid
		get_next_pid:function(callback){
			client.hget('global','nextPid',function(err,next_pid){
				callback(err,next_pid);
			});
		},
		//2.得到next_tid
		get_next_tid:function(callback){
			client.hget('global','nextTid',function(err,next_tid){
				slug = next_tid+"/"+slug;
				callback(err,next_tid);
			});
		},
		//3.在topic中插入数据，包括tid,uid,cid,mainPid,title,slug,timestamp,lastposttime,postcount=0,viewcount=0,locked=0,deleted=0,pinned=0
		insert_topic:['get_next_tid','get_next_pid',function(callback,results){
			client.hmset('topic:'+results.get_next_tid,'tid',results.get_next_tid,'uid',host_id,'cid',classification,'mainPid',results.get_next_pid,'title',msg_topic,'slug',slug,'timestamp',timestamp,
			'lastposttime',0,'postcount',0,'viewcount',0,'locked',0,'deleted',0,'pinned',0,function(err,status){
				callback(err,status);
			});
		}],
		//4.在post里面添加数据。包括：pid,uid,tid,content,timestamp,reputation=0,votes=0,editor=0,edited=0,deleted=0
		insert_post:['get_next_pid','get_next_tid',function(callback,results){
			client.hmset('post:'+results.get_next_pid,'pid',results.get_next_pid,'uid',host_id,'tid',results.get_next_tid,'content',msg_des,'timestamp',timestamp,
			'reputation',0,'votes',0,'editor',0,'edited',0,'deleted',0,function(err,status){
				callback(err,status);
			});
		}
		],
		//5.nextPid加1:
		incr_next_pid:['insert_post',function(callback){
			client.hincrby('global','nextPid',1,function(err,status){
				if(err){
					console.log("incr_next_pid");
				}
				callback(err,status);
			});
		}
		],
		//6.nextTid加1:
		incr_next_tid:['insert_topic',function(callback){
			client.hincrby('global','nextTid',1,function(err,status){
				if(err){
					console.log("incr_next_tid");
				}
				callback(err,status);
			});
		}
		],
		//7.users:postcount加1
		incr_user_post_count:['insert_post',function(callback){
			client.zincrby('users:postcount',1,host_id,function(err,status){
				if(err){
					console.log("incr_user_post_count");
				}
				callback(err,status);
			});
		}
		],
		//8.global:postcount加1
		incr_post_count:['insert_post',function(callback){
			client.hincrby('global','postcount',1,function(err,status){
				if(err){
					console.log("incr_post_count");
				}
				callback(err,status);
			});
		}
		],
		//9.global:topicCount加1
		incr_topic_count:['insert_topic',function(callback){
			client.hincrby('global','topicCount',1,function(err,status){
				if(err){
					console.log("incr_topic_count");
				}
				callback(err,status);
			});
		}
		],
		//10.categories
		add_category_id:['insert_topic','get_next_tid',function(callback,results){
			client.zadd('categories:'+classification+":tid",timestamp,results.get_next_tid,function(err,status){
				if(err){
					console.log("add_category_id");
				}
				callback(err,status);
			});
		}
		],
		//11.增加tid：followers(帖子发起者)
		add_tid_followers:['insert_topic','get_next_tid',function(callback,results){
			client.sadd('tid:'+results.get_next_tid+':followers',host_id,function(err,status){
				if(err){
					console.log("add_tid_followers");
				}
				callback(err,status);
			});
		}
		],
		//12.增加topics：tid
		add_topics_tid:['insert_topic','get_next_tid',function(callback,results){
			client.zadd('topics:tid',timestamp,results.get_next_tid,function(err,status){
				if(err){
					console.log("add_topics_tid");
				}
				callback(err,status);
			});
		}
		], 
		//13.topics:posts设置帖子回帖数，初值为0
		set_topic_post:['insert_topic','get_next_pid',function(callback,results){
			client.zadd('topics:posts',0,results.get_next_pid,function(err,status){
				if(err){
					console.log("set_topic_post");
				}
				callback(err,status);
			});
		}
		],
		//14.tid:681:read_by_uid设置被谁浏览过，初值是楼主
		set_tid_read_by_uid:['insert_topic','get_next_tid',function(callback,results){
			client.sadd('tid:'+results.get_next_tid+":read_by_uid",host_id,function(err,status){
				if(err){
					console.log("set_tid_read_by_uid");
				}
				callback(err,status);
			});
		}
		],
		//15.topics：views按照浏览人数来排列帖子
		set_topic_view:['insert_topic','get_next_tid',function(callback,results){
			client.zadd('topics:views',0,results.get_next_tid,function(err,status){
				if(err){
					console.log("set_topic_view");
				}
				callback(err,status);
			});
		}
		],
		//16.uid:552:topics添加数据
		add_uid_topics:['get_next_tid','insert_topic',function(callback,results){
			client.zadd('uid:'+host_id+':topics',timestamp,results.get_next_tid,function(err,status){
				if(err){
					console.log('add_uid_topics');
				}
				callback(err,status);
			});
		}
		],
		//17.uid:552:posts添加数据
		add_uid_posts:['get_next_pid','insert_post',function(callback,results){
			client.zadd('uid:'+host_id+':posts',timestamp,results.get_next_pid,function(err,status){
				if(err){
					console.log('add_uid_posts');
				}
				callback(err,status);
			});
		}
		],
		//topics:recent添加数据：表示最新发起的话题
		add_topics_recent:['get_next_tid','insert_topic',function(callback,results){
			client.zadd('topics:recent',timestamp,results.get_next_tid,function(err,status){
				if(err){
					console.log('add_topic_recent');
				}
				callback(err,status);
			});
		}
		],
		//用户表中的用户发帖数postcount+1
		incr_postcount:['insert_post',function(callback,results){
			client.hincrby('user:'+host_id,'postcount',1,function(err,status){
				if(err){
					console.log('incr_postcount');
				}
				callback(err,status);
			});
		}
		]
	},function(err,results){
		if(err){
			console.log(err);
			call(0);
		}
		else{
			//1代表发帖成功
			call(1);
		}
	}	
	);
}